### ISSUE TITLE
Sync README.md with latest envvar names

### ISSUE THREAD

**Issue by njpatel** [axiomhq/axiom-honeycomb-proxy#12]
e.g. readme says AXIOM_DEPLOYMENT_URL, code looks for AXIOM_URL.

**Comment by lukasmalkmus** [comment]
Which ones should we use? I prefer the long ones since they are more explicit and we do it in all our other OSS projects, as well.

**Comment by njpatel** [comment]
the short ones, across all our projects. And also, `AXIOM_URL` should be optional and `https://cloud.axiom.co` by default across all our projects too :)
